# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='siteini',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='channel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteini',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteini',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='channeldelay',
            field=models.IntegerField(default=0, verbose_name='Channel delay'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hours',
            field=models.CharField(blank=True, max_length=5, verbose_name='One show hour (debug)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='indexdelay',
            field=models.IntegerField(default=0, verbose_name='Index delay'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='keeppastdays',
            field=models.IntegerField(default=0, verbose_name='Keep last days'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_retries',
            field=models.IntegerField(default=6, verbose_name='Max retries'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='retry_timeout',
            field=models.IntegerField(default=10, verbose_name='Time between retries'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showdelay',
            field=models.IntegerField(default=0, verbose_name='Show delay'),
        ),
    ]
