# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0002_auto_20181013_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epgapp.Channel', verbose_name='Parent (if timeshifted)'),
        ),
        migrations.AddField(
            model_name='channel',
            name='broadcaster',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='epgapp.Broadcaster', verbose_name='Broadcaster'),
        ),
    ]
