# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0003_auto_20181013_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteini',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
