# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0004_siteini_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grabbers',
            options={'verbose_name': 'Siteinis configuration', 'verbose_name_plural': 'Siteinis'},
        ),
        migrations.AddField(
            model_name='grabbers',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
