# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0005_auto_20181014_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='update',
            field=models.CharField(blank=True, choices=[('', ''), ('i', 'i - Incremental'), ('l', 'l - Light'), ('s', 's - Smart'), ('f', 'f - Forced')], default='', max_length=1, verbose_name='Update type'),
        ),
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='epgapp.Category'),
        ),
    ]
