# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0006_auto_20181014_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='category',
        ),
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ManyToManyField(blank=True, default='', to='epgapp.Category'),
        ),
    ]
