# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0009_auto_20181014_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Configuration name'),
        ),
    ]
