# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0010_auto_20181014_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabbingScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('instances', models.IntegerField(default=1, verbose_name='Maximum running instances of WebGrab')),
                ('config_dir', models.CharField(max_length=512)),
                ('temp_dir', models.CharField(max_length=512)),
                ('webgrab_dir', models.CharField(max_length=512, verbose_name='Path to directory containing WebGrab EXE')),
                ('timeout', models.IntegerField(default=40)),
                ('convert_times', models.BooleanField(default=True, verbose_name='Convert times to local time')),
                ('remove_empty', models.BooleanField(default=True, verbose_name='Remove channels with no programmes')),
                ('only_title', models.BooleanField(default=True, verbose_name='Copy only title of timeshifted channels')),
                ('report', models.BooleanField(default=True, verbose_name='Generate report file')),
                ('report_name', models.CharField(max_length=128, verbose_name='wgmulti.report.json')),
                ('report_dir', models.CharField(max_length=512, verbose_name='Directory to save the report in')),
            ],
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Configurations', 'verbose_name_plural': 'WebGrab Configurations'},
        ),
        migrations.AddField(
            model_name='grabbingscheduler',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epgapp.Settings'),
        ),
    ]
