# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0014_auto_20181019_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '  Channel categories'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-name'], 'verbose_name_plural': '       Channels'},
        ),
        migrations.AlterModelOptions(
            name='grabbers',
            options={'verbose_name': 'Siteini grabber', 'verbose_name_plural': 'Siteinis'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Configurations', 'verbose_name_plural': '    WebGrab Configurations'},
        ),
        migrations.AlterModelOptions(
            name='siteini',
            options={'ordering': ['-name'], 'verbose_name_plural': '     Siteinis'},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='broadcaster',
        ),
        migrations.AlterField(
            model_name='settings',
            name='keeppastdays',
            field=models.IntegerField(blank=True, default=0, help_text='Retain the epg of a number of past days', null=True, verbose_name='Keep last N days'),
        ),
        migrations.DeleteModel(
            name='Broadcaster',
        ),
    ]
