# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0015_auto_20181019_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grabbers',
            options={'verbose_name': 'Siteini grabber', 'verbose_name_plural': 'Grabbers'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='update',
            field=models.CharField(blank=True, choices=[('', ''), ('i', 'i - Incremental'), ('l', 'l - Light'), ('s', 's - Smart'), ('f', 'f - Forced')], default='i', max_length=1, verbose_name='Update type'),
        ),
    ]
