# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0017_grabbers_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='', max_length=32),
        ),
    ]
