# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0018_channel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, verbose_name='How channel will appears in URL'),
        ),
    ]
