# Generated by Django 2.1.2 on 2018-10-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0021_auto_20181022_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grab', models.BooleanField(default=True, help_text='Specifies if the EPG grabbing is run first', verbose_name='Grab')),
                ('run', models.BooleanField(default=False, help_text='Specifies if a post process is run', verbose_name='Run')),
                ('name', models.CharField(choices=[('mdb', 'mdb'), ('rex', 'rex')], default='mdb', help_text='The name of the process to run. "mdb" or "rex"', max_length=3, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='settings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='postprocess_grab',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='postprocess_name',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='postprocess_run',
        ),
        migrations.AddField(
            model_name='settings',
            name='postprocess',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='epgapp.Postprocess'),
            preserve_default=False,
        ),
    ]
