# Generated by Django 2.1.2 on 2018-10-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0022_auto_20181026_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='mode',
        ),
        migrations.AddField(
            model_name='settings',
            name='mode',
            field=models.CharField(default='n', help_text='debug, measure, nomark, verify, wget', max_length=64, verbose_name='Modes'),
        ),
    ]
