# Generated by Django 2.1.2 on 2018-10-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0024_auto_20181026_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postprocess',
            name='id',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='postprocess',
        ),
        migrations.AddField(
            model_name='postprocess',
            name='settings',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='epgapp.Settings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
