# Generated by Django 2.1.2 on 2018-10-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0026_auto_20181026_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='postprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epgapp.Postprocess'),
        ),
    ]
