# Generated by Django 2.1.2 on 2018-10-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0027_auto_20181026_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='proxy_password',
            new_name='proxy_pass',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='postprocess',
        ),
        migrations.AddField(
            model_name='settings',
            name='grab',
            field=models.BooleanField(default=True, help_text='Specifies if the EPG grabbing is run first', verbose_name='Grab'),
        ),
        migrations.AddField(
            model_name='settings',
            name='run',
            field=models.BooleanField(default=False, help_text='Specifies if a post process is run', verbose_name='Run'),
        ),
        migrations.AddField(
            model_name='settings',
            name='type',
            field=models.CharField(choices=[('mdb', 'mdb'), ('rex', 'rex')], default='mdb', help_text='The name of the process to run. "mdb" or "rex"', max_length=3, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='Postprocess',
        ),
    ]
