# Generated by Django 2.1.2 on 2018-10-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0028_auto_20181026_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='mode',
        ),
        migrations.AddField(
            model_name='settings',
            name='mode',
            field=models.ManyToManyField(default='n', help_text='Hold the CTRL key to select multiple fields', max_length=64, to='epgapp.Modes', verbose_name='Modes'),
        ),
    ]
