# Generated by Django 2.1.2 on 2018-10-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0029_auto_20181026_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='parent',
        ),
        migrations.AlterField(
            model_name='settings',
            name='mode',
            field=models.ManyToManyField(default='n', to='epgapp.Modes', verbose_name='Modes'),
        ),
    ]
