# Generated by Django 2.1.2 on 2018-10-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0030_auto_20181026_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeshifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('xmltv_id', models.CharField(max_length=32)),
                ('offset', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epgapp.Channel')),
            ],
        ),
    ]
