# Generated by Django 2.1.2 on 2018-11-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0031_timeshifts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteini',
            options={'ordering': ['name'], 'verbose_name_plural': '     Siteinis'},
        ),
        migrations.AlterModelOptions(
            name='timeshifts',
            options={'ordering': ['offset'], 'verbose_name_plural': 'Timeshifted channels'},
        ),
        migrations.AlterField(
            model_name='timeshifts',
            name='offset',
            field=models.IntegerField(default=1, verbose_name='Offset in hours'),
        ),
        migrations.AlterField(
            model_name='timeshifts',
            name='xmltv_id',
            field=models.CharField(max_length=32, verbose_name='Channel id in XMLTV'),
        ),
    ]
