# Generated by Django 2.1.2 on 2018-11-29 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0033_auto_20181129_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteini',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, help_text='How it appears in URL', unique=True, verbose_name='Slug'),
        ),
    ]
