# Generated by Django 2.1.2 on 2018-12-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0034_auto_20181129_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Alternative channel names',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='alt_names',
            field=models.ManyToManyField(blank=True, default='', to='epgapp.Name'),
        ),
    ]
