# Generated by Django 2.1.2 on 2018-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('epgapp', '0036_auto_20181215_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='AlternativeName',
        ),
        migrations.AlterField(
            model_name='siteini',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name of siteini file'),
        )
    ]
