# Generated by Django 2.1.2 on 2018-12-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0037_auto_20181215_1313'),
    ]

    operations = [

    ]
