# Generated by Django 2.1.2 on 2018-12-15 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0038_remove_siteini_slug'),
    ]

    operations = [

    ]
