# Generated by Django 2.1.2 on 2018-12-15 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0039_auto_20181215_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteini',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, help_text='How it appears in URL', unique=False, verbose_name='Slug'),
        ),
    ]
