# Generated by Django 2.1.2 on 2018-12-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0040_auto_20181215_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteini',
            name='slug',
        ),
    ]
