# Generated by Django 2.1.2 on 2018-12-15 14:14

from django.db import migrations, models
from epgapp.models import Siteini
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0041_remove_siteini_slug'),
    ]
    
    def gen_uuid(apps, schema_editor):
        for row in Siteini.objects.all():
            row.slug = uuid.uuid4()
            row.save()
            
    operations = [

        migrations.RunPython(gen_uuid),
        
        migrations.AlterField(
          model_name='category',
          name='slug',
          field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
