# Generated by Django 2.1.2 on 2018-12-15 14:29
from django.db import migrations, models
import uuid
from epgapp.models import Siteini


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0044_siteini_slug'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Siteini.objects.all():
            row.slug = row.name
            row.save()

    operations = [

        migrations.RunPython(gen_uuid),
        

    ]
