# Generated by Django 2.1.2 on 2018-12-15 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('epgapp', '0045_siteini_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteini',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, help_text='How it appears in URL', unique=False),
        ),
    ]
