# Generated by Django 2.1.5 on 2019-01-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetvandradio', '0003_auto_20190127_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='disabled',
        ),
        migrations.AddField(
            model_name='channel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
